"""empty message

Revision ID: 1d37e9990fb4
Revises: 3b12946226d4
Create Date: 2022-04-13 12:36:50.916899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d37e9990fb4'
down_revision = '3b12946226d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_posts', sa.Column('company', sa.String(length=140), nullable=False))
    op.add_column('password_posts', sa.Column('pword', sa.Text(), nullable=False))
    op.drop_column('password_posts', 'title')
    op.drop_column('password_posts', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_posts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('password_posts', sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.drop_column('password_posts', 'pword')
    op.drop_column('password_posts', 'company')
    # ### end Alembic commands ###
