"""empty message

Revision ID: 35ac0ba7b5d9
Revises: 1d37e9990fb4
Create Date: 2022-04-13 13:07:56.277927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ac0ba7b5d9'
down_revision = '1d37e9990fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_posts', sa.Column('user_name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_posts', 'user_name')
    # ### end Alembic commands ###
